#!/usr/bin/env bash
###############################################################################
#  NoID Privacy for Linux — GitHub Action Entrypoint
#  Runs the audit, parses JSON output, generates summary, sets outputs
###############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_SCRIPT="${SCRIPT_DIR}/noid-privacy-linux.sh"

if [[ ! -f "$AUDIT_SCRIPT" ]]; then
  echo "::error::noid-privacy-linux.sh not found at ${AUDIT_SCRIPT}"
  exit 1
fi

# --- Build command ---
CMD=(sudo bash "$AUDIT_SCRIPT" --json --no-color)

# --ai flag
if [[ "${INPUT_AI:-false}" == "true" ]]; then
  # AI and JSON are mutually exclusive in the script, so we run twice:
  # once for JSON (machine-readable) and once for AI output
  AI_RUN=true
else
  AI_RUN=false
fi

# --skip sections
if [[ -n "${INPUT_SKIP:-}" ]]; then
  IFS=',' read -ra SECTIONS <<< "$INPUT_SKIP"
  for section in "${SECTIONS[@]}"; do
    section="$(echo "$section" | xargs)"  # trim whitespace
    [[ -n "$section" ]] && CMD+=(--skip "$section")
  done
fi

# Additional args
if [[ -n "${INPUT_ARGS:-}" ]]; then
  read -ra EXTRA_ARGS <<< "$INPUT_ARGS"
  CMD+=("${EXTRA_ARGS[@]}")
fi

FAIL_THRESHOLD="${INPUT_FAIL_THRESHOLD:-0}"

# --- Run audit (JSON mode) ---
echo "::group::Running NoID Privacy Audit"
echo "Command: ${CMD[*]}"

JSON_OUTPUT=""
set +e
JSON_OUTPUT=$("${CMD[@]}" 2>&1)
AUDIT_EXIT=$?
set -e

echo "::endgroup::"

# --- Parse JSON ---
if ! echo "$JSON_OUTPUT" | jq -e '.summary' >/dev/null 2>&1; then
  echo "::error::Failed to parse audit JSON output"
  echo "Raw output:"
  echo "$JSON_OUTPUT" | head -50
  exit 1
fi

SCORE=$(echo "$JSON_OUTPUT" | jq -r '.summary.score')
TOTAL=$(echo "$JSON_OUTPUT" | jq -r '.summary.total')
PASS=$(echo "$JSON_OUTPUT" | jq -r '.summary.pass')
FAIL_COUNT=$(echo "$JSON_OUTPUT" | jq -r '.summary.fail')
WARN=$(echo "$JSON_OUTPUT" | jq -r '.summary.warn')
INFO=$(echo "$JSON_OUTPUT" | jq -r '.summary.info')
DISTRO=$(echo "$JSON_OUTPUT" | jq -r '.system.distro // "unknown"')
KERNEL=$(echo "$JSON_OUTPUT" | jq -r '.system.kernel // "unknown"')
VERSION=$(echo "$JSON_OUTPUT" | jq -r '.version // "unknown"')

# --- Set outputs ---
echo "score=${SCORE}" >> "$GITHUB_OUTPUT"
echo "total=${TOTAL}" >> "$GITHUB_OUTPUT"
echo "pass=${PASS}" >> "$GITHUB_OUTPUT"
echo "fail=${FAIL_COUNT}" >> "$GITHUB_OUTPUT"
echo "warn=${WARN}" >> "$GITHUB_OUTPUT"
echo "info=${INFO}" >> "$GITHUB_OUTPUT"

# Store full JSON in output (escaped for multiline)
{
  echo "json<<NOID_JSON_EOF"
  echo "$JSON_OUTPUT"
  echo "NOID_JSON_EOF"
} >> "$GITHUB_OUTPUT"

# --- Score rating ---
if [[ "$SCORE" -ge 95 ]]; then
  RATING="🏆 EXCELLENT"
  BADGE_COLOR="brightgreen"
elif [[ "$SCORE" -ge 90 ]]; then
  RATING="🟢 SOLID"
  BADGE_COLOR="green"
elif [[ "$SCORE" -ge 80 ]]; then
  RATING="🟡 FAIR"
  BADGE_COLOR="yellow"
elif [[ "$SCORE" -ge 70 ]]; then
  RATING="🟠 NEEDS WORK"
  BADGE_COLOR="orange"
else
  RATING="🔴 CRITICAL"
  BADGE_COLOR="red"
fi

# --- Generate GitHub Summary ---
{
  echo "# 🛡️ NoID Privacy for Linux — Audit Results"
  echo ""
  echo "| | |"
  echo "|---|---|"
  echo "| **Score** | **${SCORE}%** ${RATING} |"
  echo "| **Version** | ${VERSION} |"
  echo "| **Distro** | ${DISTRO} |"
  echo "| **Kernel** | ${KERNEL} |"
  echo "| **Threshold** | ${FAIL_THRESHOLD}% |"
  echo ""
  echo "## 📊 Summary"
  echo ""
  echo "| Check | Count |"
  echo "|-------|------:|"
  echo "| ✅ Pass | ${PASS} |"
  echo "| ❌ Fail | ${FAIL_COUNT} |"
  echo "| ⚠️ Warn | ${WARN} |"
  echo "| ℹ️ Info | ${INFO} |"
  echo "| **Total** | **${TOTAL}** |"
  echo ""

  # --- Failures ---
  FAIL_FINDINGS=$(echo "$JSON_OUTPUT" | jq -r '.findings[] | select(.severity == "FAIL") | "| `\(.section)` | \(.message) |"' 2>/dev/null || true)
  if [[ -n "$FAIL_FINDINGS" ]]; then
    echo "## ❌ Failures"
    echo ""
    echo "| Section | Finding |"
    echo "|---------|---------|"
    echo "$FAIL_FINDINGS"
    echo ""
  fi

  # --- Warnings ---
  WARN_FINDINGS=$(echo "$JSON_OUTPUT" | jq -r '.findings[] | select(.severity == "WARN") | "| `\(.section)` | \(.message) |"' 2>/dev/null || true)
  if [[ -n "$WARN_FINDINGS" ]]; then
    echo "<details>"
    echo "<summary>⚠️ Warnings (${WARN})</summary>"
    echo ""
    echo "| Section | Finding |"
    echo "|---------|---------|"
    echo "$WARN_FINDINGS"
    echo ""
    echo "</details>"
    echo ""
  fi

  echo "---"
  echo ""
  echo "*Generated by [NoID Privacy for Linux](https://github.com/NexusOne23/noid-privacy-linux) v${VERSION}*"
} >> "$GITHUB_STEP_SUMMARY"

echo "✅ Audit complete: Score ${SCORE}% (${TOTAL} checks: ${PASS} pass, ${FAIL_COUNT} fail, ${WARN} warn, ${INFO} info)"

# --- AI run (separate, appended to summary) ---
if [[ "$AI_RUN" == "true" ]]; then
  echo "::group::Running AI Prompt Generation"
  AI_CMD=(sudo bash "$AUDIT_SCRIPT" --ai --no-color)
  # Add same skip sections
  if [[ -n "${INPUT_SKIP:-}" ]]; then
    IFS=',' read -ra SECTIONS <<< "$INPUT_SKIP"
    for section in "${SECTIONS[@]}"; do
      section="$(echo "$section" | xargs)"
      [[ -n "$section" ]] && AI_CMD+=(--skip "$section")
    done
  fi

  AI_OUTPUT=$("${AI_CMD[@]}" 2>&1 || true)
  echo "::endgroup::"

  # Extract AI prompt (everything after the AI marker)
  AI_PROMPT=$(echo "$AI_OUTPUT" | sed -n '/AI-READY PROMPT/,$ p' || true)
  if [[ -n "$AI_PROMPT" ]]; then
    {
      echo ""
      echo "## 🤖 AI Remediation Prompt"
      echo ""
      echo "<details>"
      echo "<summary>Click to expand AI prompt</summary>"
      echo ""
      echo '```'
      echo "$AI_PROMPT"
      echo '```'
      echo ""
      echo "</details>"
    } >> "$GITHUB_STEP_SUMMARY"
  fi
fi

# --- Threshold check ---
if [[ "$FAIL_THRESHOLD" -gt 0 ]] && [[ "$SCORE" -lt "$FAIL_THRESHOLD" ]]; then
  echo "::error::Security score ${SCORE}% is below threshold ${FAIL_THRESHOLD}%"
  exit 1
fi
